import { ChangeEvent, useMemo, useState } from "react"
import { ArrowLeft, FileArrowUp, FileText, MagnifyingGlass, NotePencil, Plus, X } from "@phosphor-icons/react"

type Doc = { id: string; title: string; meta: string; blocks: string[]; notes: string[] }
const seed: Doc[] = [
  { id: "lease", title: "Lease Agreement — 4821 Meridian Dr", meta: "Opened 9 minutes ago", blocks: ["The tenant agrees to pay rent of $2,400 per month, due on the first day of each calendar month.", "Landlord shall maintain all fixtures and structural elements in good repair throughout this lease.", "Either party may terminate this agreement by providing sixty days written notice to the other party.", "Tenant shall not make alterations to the property without prior written consent from the landlord."], notes: ["Compare the notice period with the main lease."] },
  { id: "nda", title: "NDA — Sequoia Ventures LLC", meta: "Opened 2 weeks ago", blocks: ["Confidential information includes technical plans, financial forecasts, customer data, and unreleased product materials.", "The receiving party may disclose information only to representatives who need it for evaluation."], notes: [] },
  { id: "employment", title: "Employment Contract — Mara Okafor", meta: "Opened 4 days ago", blocks: ["The employee will serve as Product Operations Lead beginning October 7, 2026.", "Either party may end employment with thirty days written notice, except in cases of material breach."], notes: ["Confirm whether remote work is limited by jurisdiction."] },
]

function App() {
  const [docs, setDocs] = useState(seed), [activeId, setActiveId] = useState("lease"), [query, setQuery] = useState(""), [marked, setMarked] = useState<string[]>([]), [note, setNote] = useState("")
  const active = docs.find(d => d.id === activeId) ?? docs[0]
  const visible = useMemo(() => docs.filter(d => d.title.toLowerCase().includes(query.toLowerCase())), [docs, query])
  const importDoc = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const doc = { id: String(Date.now()), title: file.name.replace(/\.[^/.]+$/, ""), meta: "Imported just now", blocks: ["This document is ready for a close read. Add a note or mark a passage to keep the important details in view."], notes: [] }; setDocs(current => [doc, ...current]); setActiveId(doc.id) }
  const addNote = () => { if (!note.trim()) return; setDocs(current => current.map(d => d.id === active.id ? { ...d, notes: [...d.notes, note.trim()] } : d)); setNote("") }
  return <main className="jetty">
    <aside className="library"><header><div className="wordmark">jetty<span>.</span></div><label className="import"><FileArrowUp size={15} /> import<input type="file" accept=".pdf,.txt,.md" onChange={importDoc} /></label></header><div className="library-intro"><span>YOUR LIBRARY</span><h1>Read with<br />your own mind.</h1></div><label className="search"><MagnifyingGlass size={15}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Find a document" /><kbd>⌘K</kbd></label><div className="doc-list">{visible.map(doc => <button className={doc.id === active.id ? "doc active" : "doc"} key={doc.id} onClick={() => setActiveId(doc.id)}><FileText size={16}/><span><strong>{doc.title}</strong><small>{doc.meta}</small></span></button>)}</div><button className="new-doc" onClick={() => setDocs(current => [{ id: String(Date.now()), title: "Untitled note", meta: "Created now", blocks: ["Start with the part worth remembering."], notes: [] }, ...current])}><Plus size={16}/> new document</button></aside>
    <section className="reader"><header className="reader-top"><button className="back" aria-label="Back to library"><ArrowLeft size={18}/></button><span>DOCUMENT READER</span><div><button>Focus</button><button>•••</button></div></header><div className="document-head"><p>{active.meta}</p><h2>{active.title}</h2><div className="progress"><i/><span>04 / 12</span></div></div><article className="paper"><div className="paper-mark">JT</div>{active.blocks.map((block, index) => { const id = `${active.id}-${index}`; return <button className={marked.includes(id) ? "passage marked" : "passage"} key={id} onClick={() => setMarked(current => current.includes(id) ? current.filter(x => x !== id) : [...current, id])}><span>{String(index + 1).padStart(2, "0")}</span><p>{block}</p></button> })}</article></section>
    <aside className="margin"><header><span>NOTES</span><button aria-label="Close notes"><X size={15}/></button></header><div className="note-intro"><i>✦</i><p>Keep the margins human. Your notes never change the source.</p></div><div className="notes">{active.notes.map((item, index) => <div className="note" key={item}><span>{String(index + 1).padStart(2, "0")}</span><p>{item}</p></div>)}</div><div className="composer"><NotePencil size={17}/><textarea value={note} onChange={e => setNote(e.target.value)} placeholder="Leave a thought…" /><button onClick={addNote}>Add note</button></div></aside>
  </main>
}
export default App
